# 服务器
server:
  port: 8000

# 日志
logging:
  config: classpath:log4j2.xml

# -----—Spring Cloud-----—

eureka:
  client:
    service-url:
      defaultZone: http://root:root@127.0.0.1:10000/eureka/

        









