spring:
  # 多环境配置文件
  profiles:
    active: dev
  application:
    name: pijingzhanji-order-server
# AOP
  aop:
    proxy-target-class: true
    auto: true
    
# 分页 page helper
pagehelper:
    helperDialect: Mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
# 压缩,这个属性样板打开了压缩选项，这样稍后应用到JSON正文的压缩就有保证了。
server:
  compression:
    enabled: true
    mime-types: application/json
# mybatis 枚举处理器包位置
mybatis:
  type-handlers-package: ${pijingzhanji-shop-package-prefix}.handler
    
mybatis-plus:
  mapper-locations: com/pijingzhanji/lyhy/shop/mapper/xml/*.xml
  type-aliases-package: ${pijingzhanji-shop-package-prefix}.domain
  global-config:
    # 主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 1
    # 字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    # 驼峰下划线转换
    db-column-underline: true
    # 刷新mapper 调试神器
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  
# spring boot admin 监控 start
management:
  security:
    enabled: false
# spring boot admin 监控 end
    
    
    
    
    
    
    
